### PR TITLE
UI ride-my-way

### PR DESCRIPTION
**Pull request by elineka**

### CODE REVIEW

**Review by chrisoemma — CHANGES_REQUESTED** [review]
Hi @elineka,

I have reviewed  your work and here are quick changes

1. When writing HTML files  names, start with a small letter 

2. Don't use spaces in HTML filename If the HTML file name  contains more than two words, use underscore e.g. ** driver_profile.html**

3. Commit often 

4. Include issues and project boards in your repo.

   Otherwise, nice work.

**Comment by elineka** [comment]
Noted with thanks

**Review by lupyana — CHANGES_REQUESTED** [review]
Great work @elineka 

You forgot to rectify some few things that @chrisoemma suggested

- Don't use spaces in HTML filename If the HTML file name contains more than two words, use underscore e.g. ** driver_profile.html**, you have a file called Contact driver.html. also When writing HTML files names, start with a small letter.
- You have a lot of whitespace in your code, try to minimize it.
- Try to make use of github issues on the project board.

Otherwise great work

**Comment by elineka** [comment]
Thank  I corrected

**Review by chrisoemma — APPROVED** [review]

**Review by lupyana — APPROVED** [review]
Great work @elineka

**Pull request merged**
