### PR TITLE
feature-ui

### PR DESCRIPTION
**Pull request by elineka**
1)Link home page with another page using react router dom
2)Style page with CSS

### CODE REVIEW

**Review by lupyana — COMMENTED** [review]
Hi @elineka,

I have reviewed  your work and here are some few recomendations

1. Commit more often
Dont wait till the end to commit your changes. Try to break down your task into smaller tasks and commit once each task is complete.

2. Try to describe your Pr, as in what that pr is for. What changes have you done so that a reviewer may know what to check.


   Otherwise, nice work.

**Comment by lupyana** [comment]
> Hi @elineka,
> 
> I have reviewed your work and here are some few recomendations
> 
> 1. Commit more often
>    Dont wait till the end to commit your changes. Try to break down your task into smaller tasks and commit once each task is complete.
> 2. Try to describe your Pr, as in what that pr is for. What changes have you done so that a reviewer may know what to check.
>    Otherwise, nice work.

Also try to make use of the project board to document your tasks

**Comment by elineka** [comment]
Noted with thanks and I will make adjustment

**Review by elineka — COMMENTED** [review]
1) Commited often
2)  Write about pull request
3) Using the project board issue

**Comment by elineka** [comment]
@lupyana  I added description about a pull request, committed often and using project board to document amy tasks. Can you review and merge my pull request

**Comment by lupyana** [comment]
@elineka  Great work

If you get time review [this](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
Also it is good practice to write the action in your commit message like add ..., improve ... which will help someone to know what that commit does.

But so far so good.

**Review by lupyana — APPROVED** [review]
Keep up the good work.

**Comment by elineka** [comment]
Thank you @Lupyana

**Pull request merged**
